services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buildlayoutviewer
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d buildlayoutviewer"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3435:3435"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/buildlayoutviewer
      NEXT_PUBLIC_ROJECT_ROOT: /data
    volumes:
      - .:/app

volumes:
  postgres_data:
