services:
  db:
    container_name: unity-buildlayout-viewer-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-buildlayoutviewer}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-buildlayoutviewer}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: unity-buildlayout-viewer
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    ports:
      - "${PORT:-3435}:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env


volumes:
  postgres_data:
